### PR TITLE
add support for wrapped lines in files with DOS/windows type (CR-LF) …

### PR DESCRIPTION
**Pull request by zoltanp**
…line endings

The use case for this functionality is the following type of source code:

```
#if defined(FOO) && defined(BAR) && \\\r\n
   defined(BAZ)
something;
#endif
```

### CODE REVIEW

**Comment by BR903** [comment]
The code change as written won't quite work correctly, as the lexer needs to know to skip over the "\\\r\n" sequence.

(To be clear, the use case for this code change is specifically in a situation in which a DOS file is being read by a Unix binary. The existing code already handles DOS files correctly under DOS/windows.)

**Comment by zoltanp** [comment]
I have seen that the preprocessor works correctly on wrapped lines with native Unix line endings. Unfortunately I have to deal with files that have DOS/Windows line endings on Unix-like machine, and for compatibility reasons I have to keep the line endings in original format.

One workaround would be to convert the files to Unix line endings, run cppp, and then convert them back to DOS line endings... On the other hand, it would be nice to have cppp work "out of the box".

If I understand correctly, for the case of "\\\n", the escape sequence is kept in the buffer, and then the lexer skips this sequence. The same should be done for "\\\r\n"?

Also, on DOS/Windows, how does this skipping work? I have not seen any explicit reference to it.

**Comment by BR903** [comment]
> Also, on DOS/Windows, how does this skipping work? I have not seen any explicit reference to it.

The C standard requires that stdio file I/O will translate whatever the platform uses for line endings to "\n" when reading files (and map "\n" back again when writing files), presuming the file was opened in text mode. (This is why on Unix there is no difference between text mode and binary mode files.)

I've just checked in a change that has the functionality you requested. Let me know how that works for you.

**Comment by zoltanp** [comment]
Wow, thanks a lot! It works perfectly.

**Pull request closed without merging**
